apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-assessment
resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
images:
  - name: registry.example.invalid/platform-assessment
    newName: registry.example.invalid/platform-assessment
    newTag: REPLACE_WITH_GIT_SHA
