apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-assessment
  namespace: platform-assessment
  labels:
    app.kubernetes.io/name: platform-assessment
    app.kubernetes.io/instance: platform-assessment
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-assessment
      app.kubernetes.io/instance: platform-assessment
