apiVersion: v1
kind: Service
metadata:
  name: platform-assessment
  namespace: platform-assessment
  labels:
    app.kubernetes.io/name: platform-assessment
    app.kubernetes.io/instance: platform-assessment
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-assessment
    app.kubernetes.io/instance: platform-assessment
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
