apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-assessment
  namespace: platform-assessment
  labels:
    app.kubernetes.io/name: platform-assessment
    app.kubernetes.io/instance: platform-assessment
automountServiceAccountToken: false
